apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: spark-py-job-argo
spec:
  entrypoint: submit-spark-job
  templates:
  - name: submit-spark-job
    container:
      image: bitnami/kubectl:latest   # This has kubectl pre-installed
      command: [sh, -c]
      args:
        - |
          echo "Submitting SparkApplication..."
          kubectl apply -f - <<EOF
          apiVersion: sparkoperator.k8s.io/v1beta2
          kind: SparkApplication
          metadata:
            name: spark-py-job-argo
            namespace: default
          spec:
            type: Python
            pythonVersion: "3"
            mode: cluster
            mainApplicationFile: local:///opt/spark/pi.py
            image: abhilash2018/spark-py-app
            imagePullPolicy: IfNotPresent
            sparkConf:
              spark.ui.port: "4040"
            sparkVersion: 3.5.5
            driver:
              labels:
                version: 3.5.5
              cores: 1
              memory: 512m
              serviceAccount: spark-operator-spark
            executor:
              labels:
                version: 3.5.5
              instances: 1
              cores: 1
              memory: 512m
          EOF
