apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # You can give the ClusterRole a custom name
  name: spark-operator-role
rules:
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications"]
  verbs: ["create", "get", "list", "update", "delete"]
